2023-10-10 09:01:01,737 ERROR 22799 [-/127.0.0.1/-/60ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 22799
hostname: xjswwdeMBP

2023-10-10 09:37:13,899 ERROR 23667 [-/127.0.0.1/-/9ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'priority' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `report_list`(`reportName`, `LargeCategory`, `TimeOn`, `endTime`, `priority`, `createTime`) VALUES('test', '周期性', '2023-10-10T00:00:00+08:00', '2023-12-20T00:00:00+08:00', 99, '2023-10-10 09:37:13.889')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'priority' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `report_list`(`reportName`, `LargeCategory`, `TimeOn`, `endTime`, `priority`, `createTime`) VALUES('test', '周期性', '2023-10-10T00:00:00+08:00', '2023-12-20T00:00:00+08:00', 99, '2023-10-10 09:37:13.889')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 23667
hostname: xjswwdeMBP

2023-10-10 09:44:18,026 ERROR 23667 [-/127.0.0.1/-/72ms POST /api/report/list] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'bigdata_period.bigdata_period' doesn't exist
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:23:39
    at new Promise (<anonymous>)
    at BigDataService.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:11:10)
    at BigDataController.getReportList (/Users/xujiashuang/Desktop/bigdata-server/app/controller/bigdata.js:8:40)
    sql: select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'bigdata_period.bigdata_period' doesn't exist"
sqlState: "42S02"
index: 0
sql: "select * from bigdata_period where reportType = 3 order by createTime desc limit 0,10"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_NO_SUCH_TABLEError"
pid: 23667
hostname: xjswwdeMBP

2023-10-10 10:38:55,150 ERROR 25947 [-/127.0.0.1/-/19ms POST /api/report/addsql] nodejs.TypeError: Cannot create property 'headers' on string '没有任务id'
    at cors (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_@koa_cors@3.4.3@@koa/cors/index.js:116:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/xujiashuang/Desktop/bigdata-server/node_modules/_koa@2.14.2@koa/lib/application.js:160:16

pid: 25947
hostname: xjswwdeMBP

2023-10-10 10:43:23,644 ERROR 26035 [-/127.0.0.1/-/9ms POST /api/report/createtask] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'priority' in 'field list'
    at Sequence._packetToError (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_mysql@2.18.1@mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.query (node:internal/util:346:12)
    at RDSClient._query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/client.js:33:33)
    at RDSClient.query (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:62:31)
    at RDSClient.insert (/Users/xujiashuang/Desktop/bigdata-server/node_modules/_ali-rds@5.1.2@ali-rds/lib/operator.js:159:27)
    at /Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:110:41
    at new Promise (<anonymous>)
    at BigDataService.createTask (/Users/xujiashuang/Desktop/bigdata-server/app/service/bigdata.js:108:10)
    sql: INSERT INTO `report_list`(`reportName`, `LargeCategory`, `TimeOn`, `endTime`, `priority`, `createTime`) VALUES('测试流程', '周期性', '2023-10-10T00:00:00+08:00', '2024-11-10T00:00:00+08:00', 99, '2023-10-10 10:43:23.635')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'priority' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `report_list`(`reportName`, `LargeCategory`, `TimeOn`, `endTime`, `priority`, `createTime`) VALUES('测试流程', '周期性', '2023-10-10T00:00:00+08:00', '2024-11-10T00:00:00+08:00', 99, '2023-10-10 10:43:23.635')"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 26035
hostname: xjswwdeMBP

